#!/bin/bash
#set -x

switch=br0
log=/tmp/q.log

echo -e '\n' $(date +%s) >> $log

if [ -n "$1" ]; then
	# Remove tap0 interface from bridge
	/sbin/ip link set $1 down 2>&1 >> $log
	ovs-vsctl del-port $switch $1 2>&1 >> $log
else
	echo "Error: no interface specified"	2>&1 >> $log
	exit 1
fi

exit 0
